import { getById, queryAll, queryOne } from "../../utils/dom";

export interface SpriteElements {
  imageSelect: HTMLSelectElement;
  pickImage: HTMLButtonElement;
  rows: HTMLInputElement;
  cols: HTMLInputElement;
  gridPresets: HTMLButtonElement[];
  resetGridLines: HTMLButtonElement;
  regionX: HTMLInputElement;
  regionY: HTMLInputElement;
  regionW: HTMLInputElement;
  regionH: HTMLInputElement;
  regionFull: HTMLButtonElement;
  autoTrim: HTMLInputElement;
  autoExpand: HTMLInputElement;
  autoBgMode: HTMLSelectElement;
  autoTrimMode: HTMLSelectElement;
  autoThreshold: HTMLInputElement;
  detectBounds: HTMLButtonElement;
  autoExpandToggle: HTMLElement;
  boundaryAdd: HTMLButtonElement;
  boundaryEdit: HTMLButtonElement;
  boundaryDelete: HTMLButtonElement;
  boundaryPanel: HTMLElement;
  boundaryTitle: HTMLElement;
  boundaryLeft: HTMLInputElement;
  boundaryTop: HTMLInputElement;
  boundaryRight: HTMLInputElement;
  boundaryBottom: HTMLInputElement;
  boundaryAnchorX: HTMLInputElement;
  boundaryAnchorCenter: HTMLButtonElement;
  boundaryApply: HTMLButtonElement;
  boundaryCancel: HTMLButtonElement;
  boundaryClose: HTMLButtonElement;
  boundaryEditorDelete: HTMLButtonElement;
  spriteSidebar: HTMLElement;
  previewGrid: HTMLButtonElement;
  loadSplit: HTMLButtonElement;
  thumbnailList: HTMLElement;
  selectAll: HTMLButtonElement;
  invert: HTMLButtonElement;
  clear: HTMLButtonElement;
  canvas: HTMLCanvasElement;
  placeholder: HTMLElement;
  prevFrame: HTMLButtonElement;
  playPause: HTMLButtonElement;
  nextFrame: HTMLButtonElement;
  fpsSlider: HTMLInputElement;
  fpsLabel: HTMLSpanElement;
  scaleSlider: HTMLInputElement;
  scaleLabel: HTMLSpanElement;
  frameInfo: HTMLSpanElement;
  frameSizeInfo: HTMLSpanElement;
  export: HTMLButtonElement;
}

export function cacheSpriteElements(): SpriteElements {
  return {
    imageSelect: getById<HTMLSelectElement>("sprite-image-select"),
    pickImage: getById<HTMLButtonElement>("btn-pick-image"),
    rows: getById<HTMLInputElement>("rows-input"),
    cols: getById<HTMLInputElement>("cols-input"),
    gridPresets: queryAll<HTMLButtonElement>(".grid-preset"),
    resetGridLines: getById<HTMLButtonElement>("btn-reset-grid-lines"),
    regionX: getById<HTMLInputElement>("region-x-input"),
    regionY: getById<HTMLInputElement>("region-y-input"),
    regionW: getById<HTMLInputElement>("region-w-input"),
    regionH: getById<HTMLInputElement>("region-h-input"),
    regionFull: getById<HTMLButtonElement>("btn-region-full"),
    autoTrim: getById<HTMLInputElement>("auto-trim-checkbox"),
    autoExpand: getById<HTMLInputElement>("auto-expand-checkbox"),
    autoBgMode: getById<HTMLSelectElement>("auto-bg-mode-select"),
    autoTrimMode: getById<HTMLSelectElement>("auto-trim-mode-select"),
    autoThreshold: getById<HTMLInputElement>("auto-trim-threshold-input"),
    detectBounds: getById<HTMLButtonElement>("btn-detect-bounds"),
    autoExpandToggle: getById("auto-expand-toggle"),
    boundaryAdd: getById<HTMLButtonElement>("btn-boundary-add"),
    boundaryEdit: getById<HTMLButtonElement>("btn-boundary-edit"),
    boundaryDelete: getById<HTMLButtonElement>("btn-boundary-delete"),
    boundaryPanel: getById("boundary-editor-panel"),
    boundaryTitle: getById("boundary-editor-title"),
    boundaryLeft: getById<HTMLInputElement>("boundary-left-input"),
    boundaryTop: getById<HTMLInputElement>("boundary-top-input"),
    boundaryRight: getById<HTMLInputElement>("boundary-right-input"),
    boundaryBottom: getById<HTMLInputElement>("boundary-bottom-input"),
    boundaryAnchorX: getById<HTMLInputElement>("boundary-anchor-x-input"),
    boundaryAnchorCenter: getById<HTMLButtonElement>("btn-boundary-anchor-center"),
    boundaryApply: getById<HTMLButtonElement>("btn-boundary-editor-apply"),
    boundaryCancel: getById<HTMLButtonElement>("btn-boundary-editor-cancel"),
    boundaryClose: getById<HTMLButtonElement>("btn-boundary-editor-close"),
    boundaryEditorDelete: getById<HTMLButtonElement>("btn-boundary-editor-delete"),
    spriteSidebar: queryOne<HTMLElement>(".sprite-sidebar"),
    previewGrid: getById<HTMLButtonElement>("btn-preview-grid"),
    loadSplit: getById<HTMLButtonElement>("btn-load-split"),
    thumbnailList: getById("thumbnail-list"),
    selectAll: getById<HTMLButtonElement>("btn-select-all"),
    invert: getById<HTMLButtonElement>("btn-invert"),
    clear: getById<HTMLButtonElement>("btn-clear-sel"),
    canvas: getById<HTMLCanvasElement>("preview-canvas"),
    placeholder: getById("preview-placeholder"),
    prevFrame: getById<HTMLButtonElement>("btn-prev-frame"),
    playPause: getById<HTMLButtonElement>("btn-play-pause"),
    nextFrame: getById<HTMLButtonElement>("btn-next-frame"),
    fpsSlider: getById<HTMLInputElement>("fps-slider"),
    fpsLabel: getById<HTMLSpanElement>("fps-label"),
    scaleSlider: getById<HTMLInputElement>("scale-slider"),
    scaleLabel: getById<HTMLSpanElement>("scale-label"),
    frameInfo: getById<HTMLSpanElement>("frame-info"),
    frameSizeInfo: getById<HTMLSpanElement>("frame-size-info"),
    export: getById<HTMLButtonElement>("btn-export"),
  };
}
